### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by fidian** [MtMNC/Bionicle-Fonts#1]
What is the licensing on the fonts? Did you create these yourself? If so, it would be really nice to know if the fonts are able to be used for personal or commercial works without downloading and inspecting the flags on the file (assuming those flags are set properly).

**Comment by MtMNC** [comment]
Yes I created the actual fonts myself using the Fontello service. I don't believe it set relevant flags on those fonts (although I could be incorrect). I also created the glyphs myself, but they are adapted from other images.

I created the Matoran glyphs based on fan images available on biosector01.com--which, by virtue of being personal works uploaded to biosector01.com, should be available under the GNU Free Documentation License 1.3.

I also made the Okoto glyphs based on images that the bzpower.com user jed1ndy created. He gave me permission to adapt the symbols into a font, to use the font on biosector01.com, and to disseminate the font. If pressed further I would have to defer to him regarding licensing.

Is there a particular project you're hoping to use these for? Just wondering because Bionicle fonts are a niche interest. I would hesitate to use these fonts on commercial works since they are based on media from the Bionicle property, which is owned by The Lego Group. However The Lego Group is generally fine with--and even encourages--fans to adapt Lego media for personal or noncommercial works.

**Comment by fidian** [comment]
My goal was to get a license file committed to the repository or information added to the README file. The intended uses are for a cipher site, allowing people to translate their words into and out of these characters, and a cipher book for geocachers (free PDF downloads, not published). Using a font would make both of these goals much easier, but I always look up and understand the licensing on the fonts before I add them to anything.

I am not a lawyer, but it seems like your work is covered by "fair use" when not used for commercial purposes. If I were publishing a book with many different codes, I think it would be beneficial to get permission from you (the font owner) and The LEGO group. I don't know if the intermediate person for Okoto would really be needed because they didn't originate the images, but ... again, I'm not a lawyer. 

From talking to laywers, your work is your own, even though you based it on images. You've designed the fonts yourself and you didn't tweak another person's font in order to make yours. You should be safe to pick a different license for your work. Also, some licenses explicitly prohibit people from suing you (eg. the Apache license), so your license selection may help cover you from legal exposure.

So, if these fonts were licensed by you to be used in non-commercial works and that information was placed in the repository, that would be great. I know they are on GitHub and the nature of everything on GitHub is that people can use the work, but I want to make sure I know the terms and would wait for you to license the fonts before I start using them.

**Comment by MtMNC** [comment]
Hey that's a cool use idea! I'm afraid I'm going to be pretty busy for these next few weeks to really dig into licensing issues in earnest. I'll look into that though and be more explicit about licensing. Props for being conscious of this sort of thing!

In the meantime I'd say go for it with the Matoran fonts, but I understand why you'd be hesitant. If you're concerned you can always drop a link back here I guess. Alternatively, there are other fonts floating around online with the same symbols that have seen a lot more use than mine--and people haven't gotten in trouble (as far as I know) for using them. At least then you know the font has a cleaner track record so to speak. ([MataNui](https://www.bzpower.com/ref.php?ID=472) is one that comes to mind.)

Regarding the Okoto fonts, I've reached out to jed1ndy just in case. That case is a little weird because (if I recall correctly) he may have played a role in deciphering the symbols in addition to making clean images of them. I wouldn't feel right giving you explicit permission without consulting with him first.

**Comment by MtMNC** [comment]
Sorry for the late response. That one's on me, not jed1ndy. Anyway, yes, jed1ndy finds your use fine:

"I would be fine with him (or anybody, really) using the font. Part of the reason I initially made the symbols and continued to work on them was to let as many people possible have access to it, in much the same way as the Matoran alphabet."

Unfortunately I still won't have time to look into licensing for a while.

**Comment by danny316p** [comment]
I'll second the need for licensing. I can think of a few places we could use these...
1. It'd be awesome to be able to plug this in my LEGO and Open Source presentation ( https://github.com/danny316p/LEGO_and_Open_Source ), since this is very much in that spirit even if it isn't technically OS by license.
2. There's a BZPower GitHub organization now, and that seems like an appropriate place to host this repository.
3. We could see about doing an update of the old Mata Nui Alphabet Decoder on BZP (see http://bzpower.com/ref.php?ID=1050 ) with all the newer fonts.

**Comment by MtMNC** [comment]
@fidian @danny316p Do you have particular licenses in mind? My concern (without extensive knowledge on the subject) is that the licenses that GitHub suggests allow commercial use. I don't feel comfortable allowing that since the glyphs are adapted from TLG's. Maybe CC BY-NC-SA 4.0? Or would that be too restrictive?

**Comment by fidian** [comment]
I am unsure. The license you specify says it is for original works. I don't know if this would constitute an original work or a derivative work. Personally, I think I am leaning towards derivative work, though an argument could easily be made that LEGO has not been defending their copyright claims in general regarding these characters. Plus Bionicle has been discontinued from what I read.

I also do not see any mention of who owns the intellectual property of the glyphs. It might be in The Official Guide to Bionicle book, but I do not own a copy of it so I can't check out the first page.

A big part of the lawsuits for copyright on the Internet, in my experience, is where one person made money off another person's work. Your idea of picking a license that has the "NC" bits in it for NonCommercial is excellent. As for further guidance, I would suggest you follow your heart. Having attribution and the share alike clauses may restrict who wants to use your font, but perhaps you're ok if everyone else goes out and uses a different font instead of yours. This choice is entirely up to you.

Thanks for considering the addition of a license to your repository.

**Comment by fabianmendes** [comment]
Hi, nice to meet you people. @MtMNC good work at here, bro!

Ok guys, I suggest the [Attribution-NonCommercial 4.0 International](https://creativecommons.org/licenses/by-nc/4.0/) (CC BY-NC 4.0) because it's international and preserves the author and its willness. Also it must not to be commercial, first because the rights are principal of LEGO own and second because our author should don't want to, it's a "Creative Commons creation"; open-sources for free use after all.

So, in this case, I think is better to lincense it under the [Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) (CC BY-NC-SA 4.0), letting knowing to the rest of users that there were changes after the earlier author's version/creation.

Thoughtfully,

~V. Fabian T. Mendes C.

**Comment by danny316p** [comment]
Now that that pull request has been merged, it's probably time to mark this issue as resolved.
